sudo: required
services:
    - docker
before_install:
    - docker build -t ashishyete/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true ashishyete/docker-react npm run test -- --coverage